#!/usr/bin/env bash
# install.sh — vendor mercury-tools into a consuming repo at a PINNED commit.
#
# Run from the root of the consuming repo:
#   curl -sSL https://raw.githubusercontent.com/aivee-is-a-fool/mercury-tools/main/install.sh | bash
#   ./install.sh v0.1.0          # or any tag, branch or sha
#
# Leaves behind vendor/mercury-tools/ containing the tools and a lock file that
# records the resolved commit sha and the sha256 of every vendored file. The
# lock is the point: without it, "which copy are you running" is unanswerable,
# and two agents who both say "I have check-liveness.sh" may not have the same
# one. Commit vendor/ and the lock; that is what makes the answer checkable by
# someone else.

set -euo pipefail

REPO="aivee-is-a-fool/mercury-tools"
REF="${1:-main}"
DEST="vendor/mercury-tools"

command -v curl >/dev/null || { echo "install: curl required" >&2; exit 1; }
command -v tar  >/dev/null || { echo "install: tar required" >&2; exit 1; }
command -v sha256sum >/dev/null || { echo "install: sha256sum required" >&2; exit 1; }

# Resolve the ref to an immutable sha BEFORE downloading, so the lock records
# what was actually fetched rather than what was asked for. A branch name moves;
# a sha does not.
SHA=$(curl -sSL "https://api.github.com/repos/$REPO/commits/$REF" \
      | sed -n 's/^  "sha": "\([0-9a-f]\{40\}\)",$/\1/p' | head -n1)
[[ -n "$SHA" ]] || { echo "install: could not resolve ref '$REF' in $REPO" >&2; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

curl -sSL "https://codeload.github.com/$REPO/tar.gz/$SHA" | tar -xz -C "$TMP"
SRC="$TMP/$(basename "$REPO")-$SHA"
[[ -d "$SRC/tools" ]] || { echo "install: archive has no tools/ directory" >&2; exit 1; }

rm -rf "$DEST"
mkdir -p "$DEST"
cp -r "$SRC/tools" "$DEST/"
cp "$SRC/VERSION" "$DEST/VERSION"
chmod +x "$DEST"/tools/*.sh

LOCK="$DEST/mercury-tools.lock"
{
    echo "# mercury-tools lock — generated by install.sh, do not hand-edit"
    echo "repo $REPO"
    echo "requested $REF"
    echo "commit $SHA"
    echo "version $(cat "$DEST/VERSION")"
    echo "installed $(date -Is)"
    # sha256sum marks binary mode with a leading "*" on the filename (Git Bash
    # does this, GNU coreutils on Linux does not). Normalise it out, or the lock
    # is unparseable on the other platform. Found by running install.sh and
    # having verify.sh go red on a copy it had just written itself.
    ( cd "$DEST" && find tools -type f | sort | xargs sha256sum | sed "s/ [*]/  /" )
} > "$LOCK"

echo "installed $REPO @ ${SHA:0:7} (version $(cat "$DEST/VERSION")) into $DEST"
echo "lock: $LOCK — commit it, then run ./verify.sh from the repo root to check the copy still matches"
